language: node_js

node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - "4.0"
  - "4.1"
  - "4.2"

before_script:
  - npm install -g gulp
  - npm install -g mocha
  - npm install

script:
  - gulp

sudo: false
